<div class="page-margin">
  <div class="row">
    <div class="elavenn_sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
    <div class="col-md-7 middlecol">
    
	<?php if ($wo['config']['afternoon_system'] == 1) { ?>
      <div class="alert alert-dismissible greetalert hidden" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="setCookie('day_status', '1', 3);"><span aria-hidden="true">&times;</span></button>
        <div id="daynightmsg"></div>
      </div>
	  <?php } ?>
	  
      <?php if ($wo['config']['user_status'] == 1) { ?>
      <div class="wow_content user-status-home wow_home_stories">
        <ul class="status-list">
          <?php
            if ($wo['config']['user_status'] == 1) {
            	$get_user_status = Wo_GetFriendsStatus(array('limit' => 4));
            	if (!empty($get_user_status)) {
            ?>
          <?php
            foreach ($get_user_status as $key => $wo['user_status']) {
            	echo Wo_LoadPage('home/user-status');
            	for($x = count($get_user_status); $x <= 4; $x++) { ?>
          <li class="wo_stories_empty_container">
            <div class="wo_stories_empty_profile">
              <?php
                ?>
            </div>
          </li>
          <?php }
            }
            }else{ for ($x = count($get_user_status); $x <= 4; $x++) {
			  ?>
          <li class="wo_stories_empty_container" style="height: 178.96px; min-width: 18.45%;width: 18.45%;">
            <div class="wo_stories_empty_profile">
              <?php
                ?>
            </div>
          </li>
          <?php }}	?>
          <?php } ?>
		</ul>
		<a href="<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>" data-ajax="?link1=create-status" class="wo_create_new_status"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 492.004 492.004"><path d="M484.14 226.886L306.46 49.202c-5.072-5.072-11.832-7.856-19.04-7.856-7.216 0-13.972 2.788-19.044 7.856l-16.132 16.136c-5.068 5.064-7.86 11.828-7.86 19.04 0 7.208 2.792 14.2 7.86 19.264L355.9 207.526H26.58C11.732 207.526 0 219.15 0 234.002v22.812c0 14.852 11.732 27.648 26.58 27.648h330.496L252.248 388.926c-5.068 5.072-7.86 11.652-7.86 18.864 0 7.204 2.792 13.88 7.86 18.948l16.132 16.084c5.072 5.072 11.828 7.836 19.044 7.836 7.208 0 13.968-2.8 19.04-7.872l177.68-177.68c5.084-5.088 7.88-11.88 7.86-19.1.016-7.244-2.776-14.04-7.864-19.12z"/></svg></a>
      </div>
      <?php 
        }
        if (Wo_IsThereAnnouncement() === true) { 
        $announcement = Wo_GetHomeAnnouncements();
        ?>
      <div class="home-announcement">
        <div class="alert alert-success" style="background-color: white;">
          <span class="close announcements-option" data-toggle="tooltip" onclick="Wo_ViewAnnouncement(<?php echo $announcement['id']; ?>);" title="<?php echo $wo['lang']['hide'];?>">
          <i class="fa fa-remove"></i>
          </span>
          <?php echo $announcement['text']; ?>
        </div>
      </div>
      <!-- .home-announcement -->
      <?php
        } 
        if($wo['loggedin'] == true) {
        	echo Wo_LoadPage('story/publisher-box');
        } 
        ?>
      <?php if (Wo_IsMobile() == true) { ?>
      <?php if ($wo['config']['order_posts_by'] == 0) { ?>
      <div class="order-by">
        <div class="dropdown">
          <?php echo $wo['lang']['store_posts_by'] ?>: <a class="dropdown-toggle" type="button" data-toggle="dropdown">
          <span class="order-text"><?php echo ($wo['user']['order_posts_by'] == 0) ? $wo['lang']['all'] : $wo['lang']['people_i_follow']; ?></span>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#" onclick="Wo_StorePosts(0);"><?php echo $wo['lang']['all'] ?></a></li>
            <li><a href="#" onclick="Wo_StorePosts(1);"><?php echo $wo['lang']['people_i_follow'] ?></a></li>
          </ul>
        </div>
      </div>
      <?php } ?>
      <?php } ?>
      <?php if ($wo['page'] == 'home') { ?>
      <div id="scroll_filter_click"></div>
      <ul class="list-group filterby" id="filterby-post">
        <li class="list-group-item hidden" contenteditable="false">Filter by</li>
        <li class="list-group-item avtive filter-by-li filter_negative_clr" onclick="Wo_FilterPostBy('all');" dir="auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
            <path d="M11 4h10v2H11V4zm0 4h6v2h-6V8zm0 6h10v2H11v-2zm0 4h6v2h-6v-2zM3 4h6v6H3V4zm2 2v2h2V6H5zm-2 8h6v6H3v-6zm2 2v2h2v-2H5z" fill="currentColor"></path>
          </svg>
        </li>
        <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('text');" dir="auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path fill="currentColor" d="M376.906 188.279l-30.903 8.248-8.253-30.918 30.903-8.249zM141.872 480H47.248L166.72 32h135.392l10.928 40.896 30.912-8.24L326.72 0H142.112L5.584 512H167.28l22.4-96h44.736v-32h-70.144z"/>
            <path fill="currentColor" d="M360.407 126.494l-30.925 8.23-8.23-30.924 30.924-8.23zM252.96 96h-37.088l-59.728 224h78.272v-32h-36.608l36.608-137.328 12.128 45.456 30.896-8.256zM410.416 224h-144v96h128c8.837 0 16 7.163 16 16v16h-64c-44.183 0-80 35.817-80 80s35.817 80 80 80h160V320c-.053-52.997-43.003-95.947-96-96zm64 256h-128c-26.51 0-48-21.49-48-48s21.49-48 48-48h96v-48c0-26.51-21.49-48-48-48h-96v-32h112c35.346 0 64 28.654 64 64v160z"/>
            <path fill="currentColor" d="M346.416 416h96v32h-96z"/>
          </svg>
        </li>
        <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('photos');" dir="auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
            <path fill="none" d="M0 0h24v24H0z"/>
            <path d="M5 11.1l2-2 5.5 5.5 3.5-3.5 3 3V5H5v6.1zm0 2.829V19h3.1l2.986-2.985L7 11.929l-2 2zM10.929 19H19v-2.071l-3-3L10.929 19zM4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm11.5 7a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z" fill="currentColor"/>
          </svg>
        </li>
        <li class="list-group-item filter-by-li"  onclick="Wo_FilterPostBy('video');" dir="auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
            <path d="M17 9.2l5.213-3.65a.5.5 0 0 1 .787.41v12.08a.5.5 0 0 1-.787.41L17 14.8V19a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v4.2zm0 3.159l4 2.8V8.84l-4 2.8v.718zM3 6v12h12V6H3zm2 2h2v2H5V8z" fill="currentColor"/>
          </svg>
        </li>
        <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('music');" dir="auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
            <path d="M15 4.582V12a3 3 0 1 1-2-2.83V2.05c5.053.501 9 4.765 9 9.95 0 5.523-4.477 10-10 10S2 17.523 2 12c0-5.185 3.947-9.449 9-9.95v2.012A8.001 8.001 0 0 0 12 20a8 8 0 0 0 3-15.418z" fill="currentColor"/>
          </svg>
        </li>
        <?php if ($wo['config']['fileSharing'] == 1) { ?>
        <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('files');" dir="auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
            <path d="M20 22H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1zm-1-2V4H5v16h14zM7 6h4v4H7V6zm0 6h10v2H7v-2zm0 4h10v2H7v-2zm6-9h4v2h-4V7z" fill="currentColor"></path>
          </svg>
        </li>
        <?php } ?>
        <?php if ($wo['config']['google_map']) { ?>
        <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('maps');" dir="auto">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
            <path d="M12 23.728l-6.364-6.364a9 9 0 1 1 12.728 0L12 23.728zm4.95-7.778a7 7 0 1 0-9.9 0L12 20.9l4.95-4.95zM12 13a2 2 0 1 1 0-4 2 2 0 0 1 0 4z" fill="currentColor"/>
          </svg>
        </li>
        <?php } ?>
        <li onclick="topFunction()" id="wo_scrolltop" title="Go to top">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 490.667 490.667">
            <path d="M252.885 24.443c-4.165-4.164-10.917-4.164-15.083 0L3.136 259.109A10.669 10.669 0 000 266.661v192a10.667 10.667 0 0018.219 7.552l227.115-227.136 227.115 227.136c4.16 4.171 10.914 4.179 15.085.019a10.667 10.667 0 003.134-7.571v-192a10.663 10.663 0 00-3.115-7.552L252.885 24.443z" fill="#1877f2"></path>
          </svg>
        </li>
      </ul>
      <?php } ?>
      <div class="btn btn-main btn-active posts-count" onclick="Wo_GetNewPosts();"></div>
      <div class="posts_load">
        <div id="posts-laoded">
          <div class="wo_loading_post">
            <div class="lightui1-shimmer">
              <div class="_2iwr"></div>
              <div class="_2iws"></div>
              <div class="_2iwt"></div>
              <div class="_2iwu"></div>
              <div class="_2iwv"></div>
              <div class="_2iww"></div>
              <div class="_2iwx"></div>
              <div class="_2iwy"></div>
              <div class="_2iwz"></div>
              <div class="_2iw-"></div>
              <div class="_2iw_"></div>
              <div class="_2ix0"></div>
            </div>
          </div>
          <div class="wo_loading_post">
            <div class="lightui1-shimmer">
              <div class="_2iwr"></div>
              <div class="_2iws"></div>
              <div class="_2iwt"></div>
              <div class="_2iwu"></div>
              <div class="_2iwv"></div>
              <div class="_2iww"></div>
              <div class="_2iwx"></div>
              <div class="_2iwy"></div>
              <div class="_2iwz"></div>
              <div class="_2iw-"></div>
              <div class="_2iw_"></div>
              <div class="_2ix0"></div>
            </div>
          </div>
        </div>
      </div>
      <!-- #posts -->
    </div>
    <!-- .col-md-8 -->
    <?php echo Wo_LoadPage('sidebar/content');?>
  </div>
</div>
<!-- .page-margin -->
<style>
  .post-youtube iframe {height: 277px !important;}
  @media(max-width: 1140px){
  .elavenn_sidebar{
  display: block;
  }
  }
</style>
<?php 
  if ($wo['user']['social_login'] == 1) { 
    echo Wo_LoadPage('modals/create-password');
  } 
  ?>
<script type="text/javascript">
  $(function() {
      loadposts();
  });
  
  // $(document).on('click', '.story-image-wrapper', function(event) {
  //   event.preventDefault();
  //   $value = $(this).parents(".story-container").attr('data-status-id');
  //   $.post(Wo_Ajax_Requests_File() + '?f=story_view', {id: $value}, function(data, textStatus, xhr) {
      	
  //   });
  // });
  
  /* Standard syntax */
  document.addEventListener("fullscreenchange", function() {
    $('video').toggleClass('active-player');
  });
  
  /* Firefox */
  document.addEventListener("mozfullscreenchange", function() {
    $('video').toggleClass('active-player');
  });
  
  /* Chrome, Safari and Opera */
  document.addEventListener("webkitfullscreenchange", function() {
    $('video').toggleClass('active-player');
  });
  
  /* IE / Edge */
  document.addEventListener("msfullscreenchange", function() {
    $('video').toggleClass('active-player');
  });
  
  
  function loadposts() {
  	$("#posts-laoded").load(Wo_Ajax_Requests_File() + '?f=load_posts', function enter() {
  		Wo_FinishBar();
  		window.fbAsyncInit = function() {
  		  FB.init({
  			appId      : '374255706379985',
  			xfbml      : true,
  			version    : 'v3.2'
  		  });
  		};
  	  	$(".post-description p, .product-description").each(function(index, el) {
  	  		$(this).readmore({
  		      speed: 75,
  		      moreLink: '<a href="#" class="hash"><?php echo $wo["lang"]["read_more"];?></a>',
  		      lessLink: '<a href="#" class="hash"><?php echo $wo["lang"]["read_less"];?></a>'
  		    });
  	  	});
  	  	$(".post-commet-textarea .textarea").triggeredAutocomplete({
  	       hidden: '#hidden_inputbox_comment',
  	       source: Wo_Ajax_Requests_File() + "?f=mention",
  	       trigger: "@" 
  	    });
  	  	$(".comment-reply textarea").triggeredAutocomplete({
  	       hidden: '#hidden_inputbox_comment_reply',
  	       source: Wo_Ajax_Requests_File() + "?f=mention",
  	       trigger: "@"
  	    });
  	    $('#load-more-posts').show();
  
  	});
  }
    <?php if ($wo['user']['social_login'] == 1) { ?>
    $(window).on("load", function (e) {
         $('#create-password').modal('show');
      });
    $(function() {
      var create_password_container = $('#create-password');
      $('form.create-password').ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=update_new_logged_user_details',
        beforeSend: function() {
          Wo_progressIconLoader($('form.create-password').find('button'));
        },
        success: function(data) {
          if (data.status == 200) {
            create_password_container.find('.error-container').html("<div class='alert alert-success'>" + data.message + "</div>");
             $('#update-username').attr('href', data.url);
             setTimeout(function() {
              $('#create-password').modal('hide');
             }, 1500);
          } else {
            var errors = data.errors.join("<br>");
            create_password_container.find('.error-container').html("<div class='alert alert-danger'>" + errors + "</div>");
          }
          Wo_progressIconLoader($('form.create-password').find('button'));
        }
      });
    });
  
  <?php } ?>
  
  <?php if (Wo_IsMobile() == true) { ?>
  function Wo_StorePosts(type) {
    if (type > 1) {
       return false;
    }
    if (type == 0) {
      $('.order-text').text('<?php echo $wo['lang']['all'] ?>');
    } else {
      $('.order-text').text('<?php echo $wo['lang']['people_i_follow'] ?>');
    }
    $('#posts-laoded').html('<div class="wo_loading_post"><div class="wo_loading_post_child"></div></div>');
    $.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {type:type}, function (data) {
      if (data.status == 200) {
        loadposts();
      }
    });
  }
  <?php } ?>
  
  function Wo_ViewAnnouncement(id) {
      var announcement_container = $('.home-announcement');
      $.get(Wo_Ajax_Requests_File() + '?f=update_announcement_views', {id:id}, function (data) {
        if (data.status == 200) {
            announcement_container.slideUp(200, function () {
              $(this).remove();
            });
        }
      });
  }
  
  function setCookie(cname, cvalue, exdays) {
      var d = new Date();
      d.setTime(d.getTime() + (exdays*60*60*1000));
      var expires = "expires="+ d;
      document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
  }
  
  function getCookieValue(a) {
      var b = document.cookie.match('(^|;)\\s*' + a + '\\s*=\\s*([^;]+)');
      return b ? b.pop() : '';
  }
  
  $(function () {
      var is_day_enabled = getCookieValue('day_status');
      var myDate = new Date();
      var hrs = myDate.getHours();
      var greet;
      var color;
  	var quote;
      if (hrs < 12) {
          greet = '<?php echo $wo['lang']['good_morning']?>, <?php echo $wo['user']['name']?> <img src="<?php echo $wo['config']['theme_url'];?>/img/park.png"/>';
          color = '#7FC583';
  		quote = '<?php echo $wo['lang']['good_morning_quote']?>';
      } else if (hrs >= 12 && hrs <= 18) {
          greet = '<?php echo $wo['lang']['good_afternoon']?>, <?php echo $wo['user']['name']?> <img src="<?php echo $wo['config']['theme_url'];?>/img/desert.png"/>';
          color = '#ffc107';
  		quote = '<?php echo $wo['lang']['good_afternoon_quote']?>';
      } else if (hrs >= 18 && hrs <= 24) {
          greet = '<?php echo $wo['lang']['good_evening']?>, <?php echo $wo['user']['name']?> <img src="<?php echo $wo['config']['theme_url'];?>/img/sea.png"/>';
          color = '#FF4F70';
  		quote = '<?php echo $wo['lang']['good_evening_quote']?>';
      }
      if (is_day_enabled != 1) {
        setTimeout(function () {
          $('#daynightmsg').html('<div class="small-texts">' + greet + '</div><p>' + quote + '</p>');
          $('.greetalert').removeClass('hidden');
        }, 100);
      }
  });
  $(document).ready(function(){
  $(".greetalert .close").remove();
  });
  //Get the button
  var scrltop = document.getElementById("wo_scrolltop");
  scrltop.style.display = "block";
  
  // When the user clicks on the button, scroll to the top of the document
  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
  
</script>