<li>
	<a class="see_all_stories" data_story_user_id="<?php echo $wo['user_status']['user_data']['user_id']?>" data_story_type="friends">
		<img class="wo_status_avatar" src="<?php echo $wo['user_status']['user_data']['avatar'];?>" alt="<?php echo $wo['user']['name'];?>">
		<img src="<?php echo $wo['user_status']['thumb']['filename'];?>" >
		<p><?php echo $wo['user_status']['user_data']['name']?></p>
	</a>
</li>